name: 'TripletFace'
margin: 1.0
epochs: 2
batch_size: 2
save_path: 'models/'
max_images_num_per_category: 10
max_images_num_per_test_category: 2
image_input_size: 224
weights_format: h5
weights_model: imagenet
pooling: avg
initial_learning_rate: 0.0001
first_decay_steps: 0.1
t_mul: 2.0
m_mul: 0.1
alpha: 0.0
pretrained_trainable_layers: 27
split_value_for_dataset: 0.9
